server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/typetaskpro
    username: postgres
    password: password
  flyway: 
    # enabled: false
  main:
    web-application-type: servlet